version: '3.7'
services:
  app:
    container_name: notebook_app
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    env_file: ./config/.env
    depends_on:
      - postgres
      - redis
    ports:
      - "80:80"
  postgres:
    container_name: notebook_db
    image: postgres:14.2-alpine3.15
    restart: on-failure
    env_file: ./config/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  redis:
    container_name: notebook_cache
    image: redis:6.2.6-alpine3.15
    restart: on-failure
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
